TRUNCATE TABLE CLIENT_MANAGER.CLIENTS
GO

INSERT INTO CLIENT_MANAGER.CLIENTS(CLIENT_SURNAME, CLIENT_NAME, GENDER, MANAGER_ID)
VALUES
('Abcd', 'Efgh', 1, 1),
('Abcd', 'Ijklm', 0, 1),
('Nopr', 'Stivw', 1, 2),
('Nopr', 'Xyz', 0, 3)
go 20

TRUNCATE TABLE CLIENT_MANAGER.CLIENT_ACCOUNTS
INSERT INTO CLIENT_MANAGER.CLIENT_ACCOUNTS(CLIENT_ID, CODE, BALANCE)
VALUES
(1, '1ABCDEFGHI', 2000.05),
(1, '2ABCDEFGHI', 1000.15),
(1, '3ABCDEFGHI', 200.40),
(2, '1BCDEFGHIj', 99.90),
(2, '2BCDEFGHIj', 5000.00)

/*
UPDATE [CLIENT_MANAGER].[USERS]
	SET PERMISSIONS_LEVEL = 1
WHERE ID = 2
*/