TRUNCATE TABLE CLIENT_MANAGER.CLIENTS

INSERT INTO CLIENT_MANAGER.CLIENTS(CLIENT_SURNAME, CLIENT_FULL_NAME)
VALUES
('Abcd', 'Abcd Efgh Ijklm'),
('Nopr', 'Nopr Stivw Xyz')
go 20

TRUNCATE TABLE CLIENT_MANAGER.CLIENT_ACCOUNTS
INSERT INTO CLIENT_MANAGER.CLIENT_ACCOUNTS(CLIENT_ID, CODE, BALANCE)
VALUES
(1, '1ABCDEFGHI', 2000.05),
(1, '2ABCDEFGHI', 1000.15),
(1, '3ABCDEFGHI', 200.40),
(2, '1BCDEFGHIj', 99.90),
(2, '2BCDEFGHIj', 5000.00)