TRUNCATE TABLE CLIENT_MANAGER.CLIENTS
GO

INSERT INTO CLIENT_MANAGER.CLIENTS(CLIENT_SURNAME, CLIENT_NAME, GENDER, MANAGER_ID)
VALUES
('Alexander', 'Smith', 1, 1),
('Sophia', 'Johnson', 0, 2),
('Ethan', 'Williams', 1, 3),
('Isabella', 'Brown', 0, 4),
('Benjamin', 'Jones', 1, 1),
('Olivia', 'Davis', 0, 2),
('William', 'Miller', 1, 3),
('Emma', 'Wilson', 0, 4),
('James', 'Taylor', 1, 1),
('Ava', 'Martinez', 0, 2),
('Michael', 'Anderson', 1, 3),
('Mia', 'Thomas', 0, 4),
('Daniel', 'White', 1, 1),
('Charlotte', 'Garcia', 0, 2),
('Matthew', 'Thompson', 1, 3),
('Amelia', 'Rodriguez', 0, 4),
('Christopher', 'Lopez', 1, 1),
('Harper', 'Perez', 1, 2),
('Jacob', 'Sanchez', 1, 3),
('Abigail', 'Scott', 1, 4),
('Nicholas', 'Lee', 1, 1),
('Emily', 'Lewis', 0, 2),
('Jackson', 'Harris', 1, 3),
('Elizabeth', 'King', 0, 4),
('Samuel', 'Carter', 1, 1),
('Madison', 'Nguyen', 1, 2),
('Joseph', 'Wright', 1, 3),
('Evelyn', 'Turner', 0, 4),
('Gabriel', 'Torres', 0, 1),
('Grace', 'Mitchell', 0, 2),
('David', 'Baker', 1, 3),
('Avery', 'Hall', 0, 4),
('John', 'Allen', 1, 1),
('Lily', 'Young', 0, 2),
('Ryan', 'Green', 1, 3),
('Chloe', 'Adams', 0, 4),
('Nathan', 'Martinez', 1, 1),
('Zoey', 'Hernandez', 0, 2),
('Joshua', 'Nelson', 1, 3),
('Stella', 'Hill', 0, 4),
('Andrew', 'Ramirez', 1, 1),
('Penelope', 'Moore', 1, 2),
('Logan', 'Gonzales', 1, 3),
('Layla', 'Perry', 0, 4),
('Anthony', 'Cook', 1, 1),
('Victoria', 'Bailey', 0, 2),
('Christian', 'Rivera', 1, 3),
('Sofia', 'Cooper', 0, 4),
('Jonathan', 'Reed', 1, 1),
('Natalie', 'Murphy', 0, 2),
('Isaac', 'Ross', 1, 3),
('Brooklyn', 'Hayes', 1, 4),
('Caleb', 'Bennett', 1, 1),
('Samantha', 'Rivera', 0, 2),
('Luke', 'Ward', 1, 3),
('Zoe', 'Foster', 0, 4),
('Oliver', 'Coleman', 1, 1),
('Aubrey', 'Long', 1, 2),
('Dylan', 'Hughes', 1, 3),
('Savannah', 'Diaz', 1, 4),
('Brandon', 'Price', 1, 1),
('Camila', 'Washington', 1, 2),
('Jeremiah', 'Butler', 1, 3),
('Maya', 'Foster', 0, 4),
('Julian', 'Barnes', 1, 1),
('Audrey', 'Brooks', 1, 2),
('Kevin', 'Powell', 1, 3),
('Leah', 'Coleman', 1, 4),
('Austin', 'Ross', 1, 1),
('Peyton', 'Simmons', 1, 2),
('Elijah', 'Patterson', 1, 3),
('Scarlett', 'Foster', 0, 4),
('Cooper', 'Richardson', 1, 1),
('Gabriella', 'Sanders', 0, 2),
('Isaac', 'Henderson', 1, 3),
('Autumn', 'Reed', 1, 4),
('Hunter', 'Murphy', 1, 1),
('Ariana', 'Watson', 0, 2),
('Zachary', 'Foster', 1, 3),
('Clara', 'Perry', 0, 4),
('Adrian', 'Nelson', 1, 1),
('Riley', 'Brooks', 0, 2),
('Lincoln', 'Ward', 1, 3),
('Naomi', 'Rivera', 0, 4),
('Carson', 'Simmons', 1, 1),
('Hailey', 'Coleman', 0, 2),
('Evan', 'Bennett', 1, 3),
('Julia', 'Perry', 0, 4),
('Hudson', 'Ramirez', 1, 1),
('Trinity', 'Sanders', 0, 2),
('Dominic', 'Phillips', 1, 3),
('Faith', 'Ross', 0, 4),
('Grayson', 'Washington', 1, 1),
('Serenity', 'Hayes', 0, 2),
('Brandon', 'Morgan', 1, 3),
('Elena', 'Richardson', 0, 4),
('Cole', 'Parker', 1, 1),
('Makayla', 'Price', 0, 2),
('Xavier', 'Cooper', 1, 3),
('Paisley', 'Morris', 0, 4);

TRUNCATE TABLE CLIENT_MANAGER.CLIENT_ACCOUNTS
INSERT INTO CLIENT_MANAGER.CLIENT_ACCOUNTS(CLIENT_ID, CODE, BALANCE)
VALUES
(1, '1ABCDEFGHI', 2000.05),
(1, '2ABCDEFGHI', 1000.15),
(1, '3ABCDEFGHI', 200.40),
(2, '1BCDEFGHIj', 99.90),
(2, '2BCDEFGHIj', 5000.00)

/*
UPDATE [CLIENT_MANAGER].[USERS]
	SET PERMISSIONS_LEVEL = 9
WHERE ID = 2
*/