/*
	CREATE SCHEMA CLIENT_MANAGER
*/
DROP TABLE IF EXISTS CLIENT_MANAGER.USERS
CREATE TABLE CLIENT_MANAGER.USERS
(
	ID INT IDENTITY(1,1),
	USER_LOGIN NVARCHAR(50),
	ENCRYPTED_PASSWORD NVARCHAR(50),
	IS_LOGED_IN BIT
)
GO
CREATE UNIQUE CLUSTERED INDEX USERS_UCI ON CLIENT_MANAGER.USERS
(
	USER_LOGIN ASC
)
GO
CREATE NONCLUSTERED INDEX USERS_NCI ON CLIENT_MANAGER.USERS
(
	ID ASC
)
GO
DROP TABLE IF EXISTS CLIENT_MANAGER.CLIENTS
CREATE TABLE CLIENT_MANAGER.CLIENTS
(
	ID INT IDENTITY(1,1),
	CLIENT_SURNAME NVARCHAR(50),
	CLIENT_FULL_NAME NVARCHAR(250),
	CLIENT_ACCOUNT INT
)
GO

CREATE UNIQUE CLUSTERED INDEX CLIENTS_UCI ON CLIENT_MANAGER.CLIENTS
(
	ID ASC
)
GO
CREATE NONCLUSTERED INDEX CLIENTS_NCI ON CLIENT_MANAGER.CLIENTS
(
	CLIENT_SURNAME ASC
)
GO