/*
	CREATE SCHEMA CLIENT_MANAGER
*/
DROP TABLE IF EXISTS CLIENT_MANAGER.USERS
CREATE TABLE CLIENT_MANAGER.USERS
(
	ID INT IDENTITY,
	USER_LOGIN NVARCHAR(50),
	ENCRYPTED_PASSWORD NVARCHAR(50),
	IS_LOGED_IN BIT
)