CREATE OR ALTER PROCEDURE CLIENT_MANAGER.CREATE_CLIENT
(
	@CLIENT_NAME VARCHAR(50),
	@CLIENT_SURNAME VARCHAR(50),
	@GENDER BIT,
	@CLIENT_ID INT OUT
)
AS BEGIN

	INSERT INTO CLIENT_MANAGER.CLIENTS(CLIENT_SURNAME, CLIENT_NAME, GENDER)
	VALUES (@CLIENT_SURNAME, @CLIENT_NAME, @GENDER)

	SELECT @CLIENT_ID = SCOPE_IDENTITY();

END;